/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "var(--surface)",
        "surface-dim": "var(--surface-dim)",
        "surface-bright": "var(--surface-bright)",
        "surface-container-lowest": "var(--surface-container-lowest)",
        "surface-container-low": "var(--surface-container-low)",
        "surface-container": "var(--surface-container)",
        "surface-container-high": "var(--surface-container-high)",
        "surface-container-highest": "var(--surface-container-highest)",
        "on-surface": "var(--on-surface)",
        "on-surface-variant": "var(--on-surface-variant)",
        "inverse-surface": "var(--inverse-surface)",
        "inverse-on-surface": "var(--inverse-on-surface)",
        "outline": "var(--outline)",
        "outline-variant": "var(--outline-variant)",
        "surface-tint": "#61549d",
        "primary": "#a99bea",
        "on-primary": "#1c0956",
        "primary-container": "#61549d",
        "on-primary-container": "#e6deff",
        "inverse-primary": "#cabeff",
        "secondary": "#ad9bfd",
        "on-secondary": "#1d0061",
        "secondary-container": "#402d88",
        "on-secondary-container": "#e6deff",
        "tertiary": "#a5a4ae",
        "on-tertiary": "#1a1b23",
        "tertiary-container": "#3a3a43",
        "on-tertiary-container": "#e3e1ec",
        "background": "var(--surface)",
        "on-background": "var(--on-surface)",
        "surface-variant": "var(--surface-container-high)",
      },
      fontFamily: {
        syne: ["Syne", "sans-serif"],
        mono: ["Space Mono", "monospace"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
}
