/**
 * Utility functions for exporting listening provenance data as JSON or Markdown downloads.
 */

export function getSpotifyWebUrl(uri) {
  if (!uri) return '#';
  const cleanUri = String(uri).replace('spotify:track:', '').trim();
  return `https://open.spotify.com/track/${cleanUri}`;
}

export function exportSummaryJSON(stats, insights) {
  const exportPayload = {
    archiveTitle: "LIFE//ARCHIVE — Personal Listening Provenance Report",
    generatedAt: new Date().toISOString(),
    datasetSource: "spotify_history.csv",
    quantitativeStats: {
      totalPlays: stats.totalPlays,
      totalHours: stats.totalHours,
      uniqueTracks: stats.uniqueTracks,
      uniqueArtists: stats.uniqueArtists,
      topArtist: stats.topArtist,
      dateRange: stats.dateRange,
      lateNightPlays: stats.lateNightPlays,
      lateNightPercentage: stats.lateNightPercentage,
      shufflePercentage: stats.shufflePercentage,
      skippedPercentage: stats.skippedPercentage,
    },
    discoveries: insights.map(i => ({
      title: i.title,
      category: i.category,
      measuredFact: i.measuredFact,
      explanation: i.explanation,
      metric: i.supportingMetric,
    })),
  };

  const dataStr = "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(exportPayload, null, 2));
  const downloadAnchor = document.createElement('a');
  downloadAnchor.setAttribute("href", dataStr);
  downloadAnchor.setAttribute("download", `LIFE_ARCHIVE_SUMMARY_${new Date().toISOString().slice(0, 10)}.json`);
  document.body.appendChild(downloadAnchor);
  downloadAnchor.click();
  downloadAnchor.remove();
}

export function exportMarkdownReport(stats, eras, insights) {
  let md = `# LIFE//ARCHIVE — Personal Listening Provenance Report\n\n`;
  md += `**Generated**: ${new Date().toLocaleDateString()} | **Source**: \`spotify_history.csv\`\n\n`;
  md += `---\n\n`;
  md += `## 1. Quantitative Summary\n\n`;
  md += `- **Total Stream Logs**: ${stats.totalPlays.toLocaleString()}\n`;
  md += `- **Total Time Listened**: ${stats.totalHours.toLocaleString()} Hours (~${Math.round(stats.totalHours/24)} days)\n`;
  md += `- **Unique Artists**: ${stats.uniqueArtists.toLocaleString()}\n`;
  md += `- **Unique Tracks**: ${stats.uniqueTracks.toLocaleString()}\n`;
  md += `- **Archival Date Range**: ${stats.dateRange.fullStr} (${stats.dateRange.days} days)\n`;
  md += `- **Anchor Artist**: ${stats.topArtist.name} (${stats.topArtist.count.toLocaleString()} plays)\n`;
  md += `- **Nocturnal Ratio (12am-5am)**: ${stats.lateNightPercentage}% (${stats.lateNightPlays.toLocaleString()} plays)\n`;
  md += `- **Shuffle Mode Rate**: ${stats.shufflePercentage}%\n\n`;

  md += `## 2. Chronological Listening Eras\n\n`;
  eras.forEach(era => {
    md += `### ${era.title} (${era.period})\n`;
    md += `*${era.subtitle}*\n\n`;
    md += `- **Plays**: ${era.stats.totalPlays.toLocaleString()}\n`;
    md += `- **Hours**: ${era.stats.totalHours.toLocaleString()}\n`;
    md += `- **Shift Note**: ${era.narrative}\n`;
    md += `- **Top Artists**: ${era.stats.topArtists.map(a => a.name).join(', ')}\n\n`;
  });

  md += `## 3. Substantiated Discoveries\n\n`;
  insights.forEach(ins => {
    md += `### ${ins.title} (${ins.category})\n`;
    md += `**Measured Fact**: ${ins.measuredFact}\n\n`;
    md += `${ins.explanation}\n\n`;
  });

  md += `---\n*Generated by LIFE//ARCHIVE Hackathon Application*\n`;

  const dataStr = "data:text/markdown;charset=utf-8," + encodeURIComponent(md);
  const downloadAnchor = document.createElement('a');
  downloadAnchor.setAttribute("href", dataStr);
  downloadAnchor.setAttribute("download", `LIFE_ARCHIVE_REPORT_${new Date().toISOString().slice(0, 10)}.md`);
  document.body.appendChild(downloadAnchor);
  downloadAnchor.click();
  downloadAnchor.remove();
}
